homepage:
  path: /
  default: { _controller: "Application:Blog:ListPostsAction" }
  methods: GET

login:
  path: /login
  default: { _controller: "App:LoginAction" }
  methods: GET|POST

dashboard:
  path: /dashboard
  default: { _controller: "App:DashboardAction" }
  methods: GET

blog:
  path: /blog
  default: { _controller: "App:Controller\\Blog\\ListPostsAction" }
  methods: GET

create_post:
  path: /blog/new
  default: { _controller: "App:Blog:CreatePostAction" }
  methods: GET|POST


update_post:
  path: /blog/article-{id}/update
  default: { _controller: "App:Blog:UpdatePostAction" }
  methods: GET|POST


blog_post:
  path: /blog/article-{id}
  default: { _controller: "App:Blog:GetPost"}
  requirements: {'id' : '\d+'}
  methods: GET


hello:
  path: /hello
  default: { _controller: "App:HelloWorld" }

