homepage:
  path: /
  default: { _controller: "Application\\Controller\\Blog\\ListPostsAction" }
  methods: GET

login:
  path: /login
  default: { _controller: "Application\\Controller\\LoginAction" }
  methods: GET|POST

dashboard:
  path: /dashboard
  default: { _controller: "Application\\Controller\\DashboardAction" }
  methods: GET

blog:
  path: /blog
  default: { _controller: "Application\\Controller\\Blog\\ListPostsAction" }
  methods: GET

create_post:
  path: /blog/new
  default: { _controller: "Application\\Controller\\Blog\\CreatePostAction" }
  methods: GET|POST


update_post:
  path: /blog/article-{id}/update
  default: { _controller: "Application\\Controller\\Blog\\UpdatePostAction" }
  methods: GET|POST


blog_post:
  path: /blog/article-{id}
  default: { _controller: "Application\\Controller\\Blog\\GetPostAction"}
  requirements: {'id' : '\d+'}
  methods: GET


hello:
  path: /hello
  default: { _controller: "Application\\Controller\\HelloWorldAction" }

