parameters:
    database.dsn:      mysql:host=localhost;port=3306;dbname=lp_dim_2016
    database.user:     root
    database.password: ~
    app.environment: dev
    app.debug: true
    security.hash_algo: sha512
